// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQVT0jvykEdfzNIOG5Y84tMWjHAekdJs',
    appId: '1:955617449752:web:028b0a49b437fef7c5706d',
    messagingSenderId: '955617449752',
    projectId: 'bellnotification1-ac39e',
    authDomain: 'bellnotification1-ac39e.firebaseapp.com',
    storageBucket: 'bellnotification1-ac39e.appspot.com',
    measurementId: 'G-Q7LTFZE043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HbEOUEf6FVGdBosDIzHOCjiD9DO4Es4',
    appId: '1:955617449752:android:14d9aa66aab56660c5706d',
    messagingSenderId: '955617449752',
    projectId: 'bellnotification1-ac39e',
    storageBucket: 'bellnotification1-ac39e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvdAAKSpgPUw6MLd7O5S-jAlJe092txk',
    appId: '1:955617449752:ios:bb61f616f21834f2c5706d',
    messagingSenderId: '955617449752',
    projectId: 'bellnotification1-ac39e',
    storageBucket: 'bellnotification1-ac39e.appspot.com',
    iosBundleId: 'com.example.bellnotification1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvdAAKSpgPUw6MLd7O5S-jAlJe092txk',
    appId: '1:955617449752:ios:e009d4905d06e232c5706d',
    messagingSenderId: '955617449752',
    projectId: 'bellnotification1-ac39e',
    storageBucket: 'bellnotification1-ac39e.appspot.com',
    iosBundleId: 'com.example.bellnotification1.RunnerTests',
  );
}
